#
dist: trusty
sudo: false
addons:
  postgresql: '9.4'
  chrome: stable
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5.0
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_edge_6.gemfile
before_install:
  - gem install bundler -v 1.14.6
matrix:
  allow_failures:
  - gemfile: gemfiles/rails_edge_6.gemfile
